### ISSUE TITLE
words containing only characters in the range a-f (hexa) are highlighted as numbers

### ISSUE THREAD

**Issue by dellagustin** [rmtiwari/ABAPSyntaxHighlighter#2]
![image](https://cloud.githubusercontent.com/assets/260113/8512862/624f615a-2356-11e5-8856-d975f26d88d2.png)

**Comment by rmtiwari** [comment]
..worth checking this one and adjust the abap definition accordinlgy https://github.com/PrismJS/prism/commit/ad010eac22ca42eae28363c627f8b6bae92eda52

**Comment by dellagustin** [comment]
does abap support literal hex numbers at all?
I think they are only supported as string (just like decimals).

**Comment by rmtiwari** [comment]
..that's correct! we don't need to handle hex numbers - those will be of type X but values are quoted similar to string.

**Comment by dellagustin** [comment]
Fixed in 491c16b0b2965d41a4bb3fd96e6a62cf5fd05a81
