### ISSUE TITLE
Highlighting of operators are missing

### ISSUE THREAD

**Issue by dellagustin** [rmtiwari/ABAPSyntaxHighlighter#3]

**Comment by dellagustin** [comment]
any special reason the operators are currently commented in Prism.languages.abap?

**Comment by rmtiwari** [comment]
..can't remember but probably down to minimalist approch ( Not too much highlighting )

**Comment by dellagustin** [comment]
Ok, can I introduce it?
If the user does not want the operators to be highlighted it is just a matter of handling it in the CSS.
I'm trying to be as much similar to the ABAP Editor in SAP Gui as possible.

**Comment by rmtiwari** [comment]
of course!..I've little bandwidth now a days to look into this but feel free to make changes or even look into fork/merge it into main prism project once it is at a decent level.

**Comment by dellagustin** [comment]
Ok, thanks, I have been trying to solve the comment/comment1 issue to use a single one. Not easy...
To keep it more compatible with the standard core I believe two different classes for comments will be needed (I'm currently using it in my project, and I renamed comment1 to eol_comment, eol stands for end of line).

**Comment by dellagustin** [comment]
fixed in d87ef792a163a94795e1fdd09803040d46cfec65
