### ISSUE TITLE
Preparation to integrate ABAP as an official extension of prism

### ISSUE THREAD

**Issue by dellagustin** [rmtiwari/ABAPSyntaxHighlighter#5]
Current version of prismABAP.js is based on the following version of prism-core from commit https://github.com/PrismJS/prism/commit/8a7157be3dceafe5e1a85819ce68e2def4338aba#diff-be553e8a1b66b66f387cb98326dbae83

Which is currently outdated.
#### The objective here is to:
- Remove the modifications made to the core in prismABAP.js
- Update the prism core used in prismABAP.js
#### Modifications
1. Why is this here? to avoid highlighting of class/structure components?
   
   ``` javascript
                     var wrapped;
   
                     /* Next line amended by PragmatiQa(Ram) */
   
                         if((token == 'keyword')&&((before.charAt(before.length-1) == '-')||(before.charAt(before.length-1) == '>')||(before.charAt(before.length-1) == '&'))){
   
                             // wrapped = match;
                             wrapped = new Token(' ', inside? _.tokenize(match, inside) : match);
                         } else{
                             wrapped = new Token(token, inside? _.tokenize(match, inside) : match);
                         }
   
                     // var wrapped = new Token(token, inside? _.tokenize(match, inside) : match);
   ```
2. Maybe this can be avoided/mitigated using an alias
   
   ``` javascript
   /* Next line added by PragmatiQa(Ram) */
   if(o.type == 'comment1'){ o.type = 'comment';}
   ```

**Comment by dellagustin** [comment]
Hello @rmtiwari , do you recall the details for the first modification?

**Comment by rmtiwari** [comment]
hmm..component/method/name of structure/class/macros having name same as an ABAP Keyword.
..may be if you use operations defn, this won't be a problem - not sure- worth checking.

**Comment by rmtiwari** [comment]
..may be if you use operations defn, this won't be a problem - worth checking.

**Comment by dellagustin** [comment]
I created a branch for this issue (update_prism_core).
In commit 05b157e4bfcf49bd13908d98faf348a891a111ab I updated the core with the latest version.
The modification 1 was kept.
Modification 2 was successfully removed with the use of an alias.

**Comment by rmtiwari** [comment]
..just to say that report RODPS_REPL_TEST from sap system is a good example for testing.

**Comment by dellagustin** [comment]
I can see that there are some class->get( ) and range structures (struct-sign, low, etc...) where the problem occurs in RODPS_REPL_TEST.

do you have a sample for macros where the problem also occurs?

I'm thinking the problem could be solved in the keyword regex by using whitespace (\s) + lookbehind instead of \b in the beginning of the keyword. Maybe consider punctuation too:

``` abap
.WRITE 'a'. " is valid
```

I think this would cover most cases.

**Comment by dellagustin** [comment]
I tested with the following RegEx for keywords, after removing modification 1.

``` javascript
  'keyword' : {
        pattern: /(\s|\.)(ALL_KEYWORDS)\b/gi,
        lookbehind: true,
    },
```

And RODPS_REPL_TEST seems to be working well.

**Comment by rmtiwari** [comment]
..good stuff! 
a few checks I would advise:
- check if performance is not too bad.
- check keywords on very start of a line in the middle of code, continuation of statement in next line with or without indentation etc. ..code snippet does not need to be syntactically correct, for highlighting to work on keywords/comments etc .

**Comment by dellagustin** [comment]
Something like:

``` abap
" Keyword at the start of the line
WRITE 'text'.

" In the middle of the code
  LOOP AT lt_table INTO ls_structure
    WHERE some_component = 1.
  ENDLOOP.

" Continuation of statement
    LOOP 
AT lt_table INTO ls_structure " I look ugly :(
WHERE some_component = 1.
  ENDLOOP.
```

Currently looks like:
![image](https://cloud.githubusercontent.com/assets/260113/8592471/d720be4e-262f-11e5-8959-c5c4c035414f.png)

(We look better than github :smiley: )
but I had to change to:

``` javascript
  'keyword' : {
        pattern: /(\s|\.|^)(ALL_KEYWORDS)\b/gi,
        lookbehind: true,
    },
```

introducing the ^ (beginning of line) so that a keyword at the very beginning is also highlighted.

**Performance** does not look to be a drag, the report you mentioned (RODPS_REPL_TEST) has almost 2000 lines and it is being highlited instantly. <br>
I also tested with a 14000 lines class. In chrome it took someting like one second (I tested with both the new and old RegEx and it seems to take the same time, maybe the old was slightly faster). I have to say though that a certain browser with the blue e logo took almost ten seconds to do it.

**Comment by dellagustin** [comment]
If that is ok for you I'll merge this branch into the master.

**Comment by rmtiwari** [comment]
..yup! please go ahead.
worth putting all these code snippets as example/visual test cases and may be make a github.io site for it. I've not made one before but will check later.

**Comment by dellagustin** [comment]
Merged. I added the examples as html file.
Now the language definition does not depend anymore on modifications to the core.
It could be integrated to prism, but I want to work on #2 and #3 first.
